[package]
name = "pow-runtime"
version = "2.0.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false

package = "sp-std"
version = '2.0.0-alpha.5'

[dependencies.runtime-io]
default-features = false

package = 'sp-io'
version = '2.0.0-alpha.5'

[dependencies.version]
default-features = false

package = 'sp-version'
version = '2.0.0-alpha.5'

[dependencies.frame-support]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.sp-session]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.balances]
default-features = false

package = 'pallet-balances'
version = '2.0.0-alpha.5'

[dependencies.generic-asset]
default-features = false

package = 'pallet-generic-asset'
version = '2.0.0-alpha.5'

[dependencies.transaction-payment]
default-features = false

package = 'pallet-transaction-payment'
version = '2.0.0-alpha.5'

# [dependencies.babe]
# default-features = false
# 
# package = 'pallet-babe'
# version = '2.0.0-alpha.5'
#
# [dependencies.sp-consensus-babe]
# default-features = false
# 
# version = '2.0.0-alpha.5'

[dependencies.executive]
default-features = false

package = 'frame-executive'
version = '2.0.0-alpha.5'

[dependencies.indices]
default-features = false

package = 'pallet-indices'
version = '2.0.0-alpha.5'

[dependencies.randomness-collective-flip]
default-features = false

package = 'pallet-randomness-collective-flip'
version = '2.0.0-alpha.5'

[dependencies.frame-system]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.timestamp]
default-features = false

package = 'pallet-timestamp'
version = '2.0.0-alpha.5'

[dependencies.sudo]
default-features = false

package = 'pallet-sudo'
version = '2.0.0-alpha.5'

[dependencies.sp-runtime]
default-features = false

package = 'sp-runtime'
version = '2.0.0-alpha.5'

[dependencies.sp-api]
default-features = false

package = 'sp-api'
version = '2.0.0-alpha.5'

[dependencies.block-builder-api]
default-features = false

package = 'sp-block-builder'
version = '2.0.0-alpha.5'

[dependencies.sp-transaction-pool]
default-features = false

version = '2.0.0-alpha.5'

[dependencies.inherents]
default-features = false

package = 'sp-inherents'
version = '2.0.0-alpha.5'

[dependencies.offchain-primitives]
default-features = false

package = 'sp-offchain'
version = '2.0.0-alpha.5'


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"generic-asset/std",
	"indices/std",
	"inherents/std",
	"offchain-primitives/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-session/std",
	"sudo/std",
	"frame-support/std",
	"frame-system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",
  	"sp-transaction-pool/std",
]
